#+TITLE: Word of Mouth

Word of mouth is menat to be a recommendation engine powered by social
recommendations. The first milestone in this direction will be to
parse recommendations on [[https://reddit.com/ifyoulikeblank][r/ifyoulikeblank]] similar to:

#+begin_quote
[IIL] Alt-J, Glass Animals, Florence + The Machine, [WEWIL?]
#+end_quote

Which should be read as /If I like Alt-J, Glass Animals and Florence +
The Machine, what else will I like/. The community than answer with
band or songs recommendations. You can see this thread for yourself
[[https://www.reddit.com/r/ifyoulikeblank/comments/9tdu7c/iil_altj_glass_animals_florence_the_machine_wewil/][here]].

This is my playground to explore:

- Modern python development environment;
- Crawler and dataset generation;
- Semi-automatic label annotation;
- Leveraging an external onthology of artists and songs;
- Tagging and hopefully attention models;
- Writing a reddit bot for the sake of it.

And now I just started a detour toward text generation to build a band
name generator.

* Reddit Crawler

You can look in =src/crawler.py= to see how to crawl a subreddit using
the pushshift api (more details in this [[https://www.textjuicer.com/2019/07/crawling-all-submissions-from-a-subreddit/][post]].

* Dataset Generation from Wikidata

You can look in =wordofmouth/gazetteer.py= to see how to generate datasets
from wikidata (more details in this [[https://www.textjuicer.com/2019/08/building-a-gazetteer-of-music-bands-using-wikidata/][post]]).

* Band Name Generator

You can look in =wordofmouth/bandaid.py= to see how to generate band
names using a recurrent neural network (more details in this post).
